chef-partners/omnibus-marketplace

files/chef-marketplace-cookbooks/chef-marketplace/libraries/helpers.rb
The only way the cloud_v2 api determines the public hostname is if a hints file with the information is passed in via knife-azure. Little to no users will be using this method when deploying from the marketplace.
We should default to the fqdn to avoid things like `"api_fqdn": ".cloudapp.net"` from happening if the user sets the hostname using `chef-marketplace-ctl hostname`.
https://github.com/chef/ohai/blob/master/lib/ohai/plugins/azure.rb#L20-L34
=> Fix how we determine the api_fqdn on azure

files/chef-marketplace-ctl-commands/register_node.rb, files/chef-marketplace-ctl-commands/upgrade.rb
OmnibusCtl was class_eval-ing the `default_config` in both commands
because it was not in the command block.  I removed both methods and
went with a simple declarative hash.
=> Fix omnibus-ctl naming collision

config/software/chef-marketplace-cookbooks.rb, config/templates/chef-marketplace-cookbooks/non_root_solo.rb.erb, config/templates/chef-marketplace-cookbooks/solo.rb.erb, files/chef-marketplace-cookbooks/chef-marketplace/libraries/helpers.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/config.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/default.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/register_node.rb, files/chef-marketplace-ctl-commands/register_node.rb
Run the embedded chef-client run with a globally accessible cache
so that unprivileged users can run the command.  This will allow
the chef-compliance core application to run the command for us
during the setup wizard.  It should also allow the opscode user
to do the same if we implement registration in chef-manage.
=> Allow running chef-marketplace-ctl register-node as a non-root user

files/chef-marketplace-cookbooks/chef-marketplace/libraries/helpers.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_automate_preconfigure.rb
right now when running a preconfigure in the build instance we'll
fail to configure certain portions of the automate and chef-server
services beacuse licensing restrictions put the load balancer into
maintencance mode without the presence of a valid license.
eventually we can preconfigure all of the services and then rotate
credentials on first boot, but for now this still cuts down on the
initial install time considerably from needing to install the
packages after boot
/cc @ryancragun
=> chef-automate: don't preconfigure

files/chef-marketplace-cookbooks/chef-marketplace/recipes/_aio_enable.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_server_aio_enable.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_upgrade_chef_server_aio.rb, files/chef-marketplace-cookbooks/chef-marketplace/templates/default/chef-server-aio.rb.erb, files/chef-marketplace-ctl-commands/spec/upgrade_ctl_spec.rb, files/chef-marketplace-ctl-commands/upgrade.rb
copies over previous recipes that handle chef-server AIO
configuration and upgrades and separates them from the
chef-server recieps that are intended for use with automate
=> [MAR-18] back-compat for aio upgrades

arm-templates/automate/createUiDefinition.json, arm-templates/automate/mainTemplate.json, arm-templates/automate/mainTemplateParameters.json, arm-templates/automate/nested/publicipaddress_existing.json, arm-templates/automate/nested/publicipaddress_new.json, arm-templates/automate/nested/storageaccount_existing.json, arm-templates/automate/nested/storageaccount_new.json, arm-templates/automate/nested/vm_password.json, arm-templates/automate/nested/vm_sshPublicKey.json, arm-templates/automate/nested/vnet_existing.json, arm-templates/automate/nested/vnet_new.json
In cases where the Solution Template supports re-using existing
resouces:
* Storage Accounts
* Public IP Adresses
* Virtual Networks
we need to require the Resource Group name when looking up references to
those resources. Previously we assumed all resources would be in our
current Resource Group, however, the UI Elements allow users to specify
matching resource types available in the specified region regardless of
their Resource Group. This resulted in launch failures when the template
tried to reference existing resources that exits in a different resource
group.
=> Require the Resource Group for existing resources

arm-templates/automate/createUiDefinition.json
There's currently an issue with Azure's UI that prevents validation from
succeeding when selecting an existing Public IP Address. There is a
hacky workaround but it isn't obvious and it definitely impacts user
performance. To that end we'll hide existing Public IP Addresses in the
UI definition until the UI bug is resolved.
=> Hide existing Public IP Addresses in UI definition

files/chef-marketplace-cookbooks/chef-marketplace/attributes/default.rb, files/chef-marketplace-cookbooks/chef-marketplace/libraries/marketplace.rb, files/chef-marketplace-cookbooks/chef-marketplace/templates/default/delivery.rb.erb
Add a sales contact configuration option and automatically set the Chef Automate expired trial contact address to the sales email.
=> [CLOUD-288] Make Chef Automate expired contact email configurable

arm-templates/automate/automate_setup.rb
opt-parser was requiring that we passed a non-empty string
to the command, which is a case that we handle later in
the script. removing this validation fixes the case where
the user does not supply a license
Signed-off-by: Stephen Delano <stephen@chef.io>
=> automate_setup: handle case with no licesne

files/chef-marketplace-cookbooks/chef-marketplace/recipes/_automate_enable.rb, files/chef-marketplace-gem/lib/marketplace/setup.rb
* Fix a bug where the Chef Server setup would fail because of a
preflight check bug in the Chef Server.
* Disable Automate Telemetry on AWS because it violates the terms
of service.
=> Fix Chef Server setup and disable Telemetry

files/chef-marketplace-cookbooks/chef-marketplace/templates/default/chef-server.rb.erb
This change overrides the Chef server pedant configuration exclude the
Chef Server's non-default SSL port. That will allow the tests to run
through the Chef Automate proxy and into the Chef Server.
It also limits SSL to TLSv1.2, which is fine because SSL is terminated
on the Chef Automate nginx. It also fixes a bug where some pedant tests
would attempt to use TLSv1.0 against the Automate nginx and it was
rejected.
Requires a stable release of the Chef Server including that includes https://github.com/chef/chef-server/pull/1278
=> [CLOUD-371] Fix pedant tests for Chef Automate AIO

Makefile, docker-compose-services.yml, docker-compose-tests.yml, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_config_api_fqdn.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_config_package_mirrors.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_config_reckoner.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_security.rb, shared/recipes/chef-client-test.rb, shared/recipes/setup-chef-client-test.rb, shared/scripts/automate-marketplace.sh, shared/scripts/chef-client-test.sh
Use `node.normal` attribute precedence where we previously used `node.set`.
Add support for converging a chef-client against the development environment.
=> Fix support for chef 13

Gemfile, Gemfile.lock, files/chef-marketplace-gem/chef-marketplace.gemspec, files/chef-marketplace-gem/lib/marketplace/reckoner/checker/automate.rb, files/reckoner/Gemfile
* Make the reckoner nodes query ES 5 compatible
* Pin the AWS SDK to version 2 until omnibus is updated and reckoner is
migrated.
=> [CLOUD-474] Fix reckoner for Automate 1.6

arm-templates/automate/mainTemplate.json, arm-templates/automate/mainTemplateParameters.json, arm-templates/automate/storageaccount_new.json
Signed-off-by: Stuart Preston <stuart@chef.io>
This change allows the existing Chef Automate solution template to be compatible with the Azure Resource Provider versions used in the TP3 refresh of Azure Stack, by downgrading some of the API versions used in the ARM template to match those deployed on Azure Stack.  
These changes will need to be staged in the usual manner prior to validation.  We already have sign off from Greg Oliver and Matt McSpirit that these are valid changes.
```
From: Matt McSpirit
Sent: 05 June 2017 22:03
To: Stuart Preston; Greg Oliver
Subject: RE: Catch-Up
Hey Stuart,
The engineers seem to think all the JSON templates look good, and advised for you to test
on Azure with the updated template.  All being well, and the testing works out fine, you should
be good to …
```
=> Azure Stack compatibility for Chef Automate solution template

files/chef-marketplace-cookbooks/chef-marketplace/recipes/_publishing_enable.rb, files/chef-marketplace-cookbooks/chef-marketplace/resources/cfn_tools.rb
As we transition our AWS offerings to use CloudFormation we'll need to
properly signal the stack when setup is completed. During publishing on
we now ensure that the tools are installed and linked.
=> [CLOUD-540] Install Cloudformation tools on AWS images

files/chef-marketplace-gem/lib/marketplace/setup.rb
There seems to be a race condition in which automate is restarting between actions and we are unable to create an enterprise. For now, we want to just retry again and add a longer delay than the default two
seconds between each retry.
Signed-off-by: Ryan Hass <rhass@users.noreply.github.com>
=> Workaround race condition in creating an enterprise

arm-templates/automate/automate_setup.rb, cloudformation/marketplace_byol.yml, files/chef-marketplace-cookbooks/chef-marketplace/attributes/default.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_upgrade_automate.rb, files/chef-marketplace-cookbooks/chef-marketplace/templates/default/biscotti_nginx_upstreams.conf.erb, files/chef-marketplace-ctl-commands/setup.rb, files/chef-marketplace-ctl-commands/upgrade.rb, files/chef-marketplace-gem/lib/marketplace/setup.rb
The main fix is to set the HOME environment variable in the cloudformation and ARM templates. 
This PR also implements a `--debug` log output for `chef-marketplace-ctl` and a `--channel` option to allow the user to specify the release channel to use for installing Chef Automate.
Fixes SUSTAIN-844
See the commit messages for complete details.
/cc @btm
=> Fix Starter Kit Download issues add improvements for debugging.

arm-templates/automate/automate_setup.rb
The chef-marketplace-ctl command was failing with a timeout during the preconfigure step as it was taking longer than the mixlib-shellout default 600 seconds to complete.
=> Increase timeout during preconfigure in Azure.

GruntFile.js, files/chef-marketplace-cookbooks/chef-marketplace/templates/default/chef-marketplace-cloud-init-setup.erb
This includes two fixes.
- The `arm-publish` command expected a different filename than what we set in the Makefile and committed. This updates the filename and Makefile to match to the rest of the parts.
- Set HOME for cloud-init scripts with Metered AWS offering.
=> Bug Fixes for Azure and AWS Metered

config/software/reckoner.rb, files/chef-marketplace-cookbooks/chef-marketplace/attributes/default.rb, files/chef-marketplace-cookbooks/chef-marketplace/libraries/helpers.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_automate_enable.rb, files/chef-marketplace-cookbooks/chef-marketplace/recipes/_reckoner_enable.rb, files/chef-marketplace-cookbooks/chef-marketplace/templates/default/sv-reckoner-run.erb, files/reckoner/.gitignore, files/reckoner/Gemfile, files/reckoner/LICENSE, files/reckoner/bin/reckoner, files/reckoner/reckoner.gemspec
The reckoner application is failing to start correctly in the lastest metered AMI submitted to AWS due to pathing issues and inability to load specific gems. This resolves the issue by using appbundler to explicitly set the gem path and pin the gem versions at runtime.
Additionally, we made use of active_support/time numeric durations without having included activesupport in the gemfile or requiring it into script resulting in undefined method errors. This fixes the calls so they can function as originally intended.
/cc @prajaktapurohit @nsdavidson
=> Appbundle Reckoner & Fix bugs in service

omnibus-test.sh
This just updates the `omnibus-test.sh` script to use tools that have been moved into the omnibus-toolchain. It also makes some changes to output to be more consistent across our omnibus projects.
=> Use new omnibus-toolchain scripts in omnibus-test.sh script

Gemfile, Gemfile.lock
This change only affects CI. The artifactory gem is required for the publish part of the build stage.
https://github.com/chef/omnibus-buildkite-plugin/issues/22
=> [ci] Add artifactory to omnibus/Gemfile
